vblog:
  data:
    elasticsearch:
      cluster-name: elasticsearch_hasaker
      cluster-nodes: 127.0.0.1:9200
      index:
        number-of-replicas: 1
        number-of-shards: 3


spring:
  messages:
    basename: i18n/messages
    fallbackToSystemLocale: false
  datasource:
    url: jdbc:mysql://localhost:3306/vblog?characterEncoding=utf8&useSSL=false
    username: root
    password: 5523
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    cluster:
      nodes: 127.0.0.1:6379,127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005


mybatis-plus:
  mapper-locations: com.hasaker.vblog.mapper
  type-aliases-package: com.hasasker.vblog.entity
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl