vblog:
  data:
    elasticsearch:
      cluster-name: elasticsearch_hasaker
      cluster-nodes: 127.0.0.1:9200
      index:
        number-of-replicas: 1
        number-of-shards: 3

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vblog?characterEncoding=utf8&useSSL=false
    username: root
    password: 5523