server:
  port: 8761 # 指定该Eureka实例的端口

spring:
  application:
    name: vblog-registry-server

eureka:
  instance:
    hostname: vblog-registry-server # 指定该Eureka实例的主机名
  # 配置关闭自我保护，并按需配置Eureka Server清理无效节点的时间间隔
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000
  client:
    # 是否要注册到其他Eureka Server实例
    register-with-eureka: false
    # 是否要从其他Eureka Server实例获取数据
    fetch-registry: false
    service-url:
      default-zone: http://localhost:9000/eureka/